name: yaml2json
version: 1.0.1
author: Kenneth Endfinger <kaendfinger@gmail.com>
environment:
  sdk: '>=1.5.0'
dependencies:
  args: '>=0.11.0+1 <1.0.0'
  yaml: '>=1.1.1 <3.0.0'
homepage: https://github.com/kaendfinger/yaml2json
description: yaml2json converter library and command line tool
executables:
  yaml2json:
